name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        user_name: GitHub Actions
        user_email: actions@github.com

    - name: Set Mapbox API key
      run: echo ${{ secrets.MAPBOX_API_KEY }} > ./build/mapbox-api-key.txt

    - name: Commit Mapbox API key
      run: |
        git add ./build/mapbox-api-key.txt
        git commit -m "Add Mapbox API key"
        git push

